"""Default configuration values."""

DEFAULT_WORLD_CONFIG = {
    "seed": 42,
    "region_count": 10,
    "civilization_count": 3,
    "relic_count": 8,
    "protagonist_count": 6,
    "active_character_count": 24,
}

DEFAULT_AI_CONFIG = {
    "provider": "siliconflow",
    "base_url": "https://api.siliconflow.cn/v1/chat/completions",
    "api_key_env": "SILICONFLOW_API_KEY",
    "model": "deepseek-ai/DeepSeek-V4-Pro",
    "temperature": 0.4,
    "max_tokens": 160,
    "request_timeout_seconds": 90,
    "thinking_budget": 32,
    "low_cost_max_tokens": 120,
    "low_cost_thinking_budget": 8,
    "medium_cost_max_tokens": 220,
    "medium_cost_thinking_budget": 16,
    "high_cost_max_tokens": 320,
    "high_cost_thinking_budget": 24,
    "observer_max_tokens": 220,
    "observer_thinking_budget": 16,
    "observer_full_max_tokens": 320,
    "observer_full_thinking_budget": 24,
    "protagonist_budget_per_week": 1,
    "active_character_budget_per_week": 0,
    "chronicler_budget_per_week": 2,
    "observation_budget_mode": "on_demand",
    "intent_llm_mode": "protagonist_only",
    "protagonist_intent_cost_tier": "medium",
    "active_intent_cost_tier": "low",
    "protagonist_intent_signal_threshold": 12,
    "active_intent_signal_threshold": 9,
    "observer_llm_mode": "truth_only",
    "observer_brief_cost_tier": "medium",
    "observer_full_cost_tier": "high",
    "observer_brief_signal_threshold": 6,
    "observer_full_signal_threshold": 8,
    "chronicler_llm_mode": "high_signal_only",
    "chronicler_cost_tier": "medium",
    "chronicle_signal_threshold": 16,
    "observer_focus_ai_enabled": False,
    "dynamic_structure_cost_tier": "medium",
}
